package exceptions;

public class Throwcf {
	
	class ThrowCF1 
	{
		public static void main(String[] args) 
		{
			System.out.println("In main");
			throw new Exception();
		}
	}

}
