package Exceptions;

public class Exceptions {

	public static void main(String[] args)throws Exception {
		// TODO Auto-generated method stub
		try {
			
			
			
			throw new Exception();
//			int a=100/0;
//			
//			int[] ar = new int[2];
//			ar[3]=1;
			
			
			
		}
		
		catch(ArithmeticException e) {
			System.out.println("arthemetic exception");

		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("ArrayIndexOutOfBounds Exception");

		}
		catch(Exception e) {
			System.out.println(e);
		}
		finally {
			System.out.println("finally done");

		}
		

	}

}
